build:
  image: node:4.2
  commands:
    - npm install

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-artifactory
    tag: latest
    when:
      branch: master

plugin:
  name: Artifactory
  desc: Publish Artifacts to Artifactory
  type: publish
  image: plugins/drone-artifactory
  labels:
    - publish
    - artifactory
