pipeline:
  build:
    image: node:4.2
    commands:
      - make install
      - make test
  coverage:
    image: plugins/coverage
    # Must match parts of the absolute path
    pattern: drone-artifactory/coverage/lcov.info
    server: https://aircover.co
    when:
      branch: master
  publish:
    image: plugins/docker
    repo: athieriot/drone-artifactory
    tag: latest
    when:
      branch: master
      
plugin:
  name: Artifactory
  desc: Publish files and artifacts to Artifactory
  type: publish
  image: athieriot/drone-artifactory
  labels:
    - artifactory
