pipeline:
  test:
    image: node:4.2
    commands:
    - make install
    - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-artifactory
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Artifactory
  desc: Publish files and artifacts to Artifactory
  type: publish
  image: plugins/drone-artifactory
  labels:
    - artifactory
