pipeline:
  build:
    image: node:carbon
    commands:
      - make install
      - make test
  docker:
    image: plugins/docker
    repo: athieriot/drone-artifactory
    tag: latest
    secrets: [ docker_username, docker_password ]
    when:
      event: push
      branch: master
      local: false

plugin:
  name: Artifactory
  desc: Publish files and artifacts to Artifactory
  type: publish
  image: athieriot/drone-artifactory
  labels:
    - artifactory
